name: Sync to LEAF CITY Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fetch from LEAF CITY Organization Repo
        run: |
          git remote add org-repo git@github.com:Leaf-City/leafcity.git
          git fetch org-repo

      - name: Merge remote changes with unrelated histories
        run: |
          git merge org-repo/main --allow-unrelated-histories

      - name: Push to LEAF CITY Organization Repo
        run: |
          git push org-repo main
