name: Sync to LEAF CITY Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add remote
        run: |
          git remote add org-repo git@github.com:Leaf-City/leafcity.git

      - name: Fetch from LEAF CITY Organization Repo
        run: |
          git fetch org-repo || true

      - name: Create initial commit if necessary
        run: |
          if [ ! -d ".git" ]; then
            git init
            touch README.md
            git add README.md
            git commit -m "Initial commit"
            git branch -M main
          fi

      - name: Push to LEAF CITY Organization Repo
        run: |
          git push org-repo main
