name: Sync to LEAF CITY Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to LEAF CITY Organization Repo
        env:
          GIT_ASKPASS: echo
          GIT_PASSWORD: ${{ secrets.LC_ACCESS_TOKEN }}
        run: |
          git remote add org-repo https://github.com/Leaf-City/leafcity.git
          git push https://github.com/Leaf-City/leafcity.git main
      
