name: Sync to LEAF CITY Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to LEAF CITY Organization Repo
        run: |
          git remote add org-repo https://github.com/Leaf-City/leafcity.git
          git push https://${{ secrets.LC_ACCESS_TOKEN }}@github.com/Leaf-City/leafcity.git main
        env:
          GITHUB_TOKEN: ${{ secrets.LC_ACCESS_TOKEN }}
